@startuml

package "iLoc Installation 1" {
	[iLoc8 Core] as Core1
	() "<<Type>> \n Interface" as Interface1
	[<<Type>> \n Adaptor 1] as Adaptor1
}

() "<<Type>> \n Service 1" as Service1

package "iLoc Installation 2" {
	[iLoc8 Core] as Core2
	() "<<Type>> \n Interface" as Interface2
	[<<Type>> \n Adaptor 2] as Adaptor2
}

() "<<Type>> \n Service 2" as Service2

() "Legend" as NoteHook
note bottom of NoteHook #White
	<<**Type**>> is one of the
	non-iLoc8 Services
	accessed by Core:
	- SMS
	- Event Storage
	- Media Storage
end note

Core1 --> Interface1: use
Interface1 <|.. Adaptor1: implement
Adaptor1 --> Service1: translate

Core2 --> Interface2: use
Interface2 <|.. Adaptor2: implement
Adaptor2 --> Service2: translate

@enduml
