@startuml

package "iLoc Installation 1" {
	() "Media Storage \n File Transfer API" as FileAPI1
	[iLoc8 Core] as Core1
	() "Media Storage Interface" as Interface1
	[Media Storage Adaptor 1] as Adaptor1
}

() "Media Storage Service 1" as Service1

[Caller App] as Caller1
[Agent App] as Agent1

package "iLoc Installation 2" {
	[iLoc8 Core] as Core2
	() "Media Storage Interface" as Interface2
	[Media Storage Adaptor 2] as Adaptor2
	() "Media Storage \n File Transfer API" as FileAPI2
}

() "Media Storage Service 2" as Service2

[Caller App] as Caller2
[Agent App] as Agent2

Core1 --> Interface1: use
Interface1 <|.. Adaptor1: implement
Adaptor1 --> Service1: translate
FileAPI1 <|.. Adaptor1: implement
Caller1 --> FileAPI1: upload
Agent1 --> FileAPI1: download

Core2 --> Interface2: use
Interface2 <|.. Adaptor2: implement
Adaptor2 --> Service2: translate
FileAPI2 <|.. Adaptor2: implement
Agent2 --> FileAPI2: download
Caller2 --> FileAPI2: upload

@enduml
