@startuml

cloud "External Telephony Services" {
	() "SMS Service" as SMS
	() "Phone Service" as PSTN
}

package "Caller Smartphone" {
	() "Phone" as CPhone
	[Caller App] as Caller
}

package "Agent Devices" {
	() "Phone" as APhone
	() "Interaction Center" as IC
	[Agent App] as Agent
}

[\n\n\n\n\niLoc8\n\n\n\n\n] as iLoc8
() "Customer-Provided \n Storage" as Storage

() "Legend" as NoteHook
note bottom of NoteHook #White
	**Arrows are coloured as follows**:
	<color:Blue>Interaction outside iLoc8
	<color:Green>Data Channel
	<color:Magenta>Video Channel
	<color:Brown>Other interaction
end note

PSTN <--> CPhone #Blue
PSTN <--> APhone #Blue

SMS <-- iLoc8 #Brown
SMS --> CPhone #Blue

CPhone -> Caller
IC -> Agent

Caller <--> iLoc8 #Green: Data \n Channel
Agent <--> iLoc8 #Green: Data \n Channel

Caller <--> iLoc8 #Magenta: Video \n Channel
Agent <--> iLoc8 #Magenta: Video \n Channel

iLoc8 --> Storage #Brown: Events
iLoc8 --> Storage #Green: Uploads

@enduml
