@startuml
!pragma horizontalLineBetweenDifferentPackageAllowed

package "Breeze Snap-Ins" {
	[SMS Adaptor] as AdSMS #DarkSeaGreen
	[iLoc8 Core] as Core #Pink
	[Media Store Adaptor] as AdMedia #DarkSeaGreen
	[Event Adaptor] as AdEvent #DarkSeaGreen

	Core <- AdSMS #Black: MQ
	Core <-> AdMedia #Black: MQ
	Core --> AdEvent #Black: MQ
}

	() "SMS Service" as SMS #Blue
	() "Event Storage" as StEvent #Blue
	() "Media Storage" as StMedia #Blue

[Caller App] as Caller #LightGoldenRodYellow
[Agent App] as Agent #LightGoldenRodYellow

() "Legend" as NoteHook
note bottom of NoteHook #White
	**Items and Acronyms**:
	- MQ: Message Queue
	- Boxes: iLoc8 Components
	- Circles: Non-iLoc8 Interfaces
	
	**Boxes Colors**:
	<back:pink>Services
	<back:DarkSeaGreen>iLoc8 Adaptors
	<back:LightGoldenRodYellow>Client Apps
	<back:Blue><color:White>Non-iLoc8
	
	**Arrows Colors**:
	<color:Blue>Interaction outside iLoc8
	<color:Brown>Caller/Agent API
	<color:Green>File Transfer API
	<color:Black>iLoc8 Internal Communication
end note

SMS <-- AdSMS #Blue: Send SMS

AdEvent --> StEvent #Blue: Store Events

AdMedia <-> StMedia #Blue: Upload \n Download

Caller <--> Core #Brown: Caller API
Agent <--> Core #Brown: Agent API

Caller --> AdMedia #Green: Upload API
AdMedia --> Agent #Green: Download API

@enduml
