@startuml
left to right direction

actor Caller
actor Agent

usecase call as "Phone Call"
usecase st as "Start iLoc8"
usecase iLoc8 as "
iLoc8
--
Data
Video
"

call .> st
st .> iLoc8

Caller -- call
call -- Agent

Caller --> st
st <-- Agent

Caller -- iLoc8
iLoc8 -- Agent

@enduml
