@startuml
left to right direction

actor Caller
actor Agent

usecase st as "Start iLoc8"
usecase sms as "Receive iLoc8 SMS"
usecase click as "Click on SMS Link"
usecase cdashb as "Caller Dashboard"
usecase adashb as "Agent Dashboard"

st .> sms
st .> adashb
sms .> click
click .> cdashb

st <-- Agent

Caller --> sms
Caller --> click

Caller -- cdashb: use
adashb -- Agent: use

@enduml
