apiVersion: v1
kind: Pod
metadata:
  name: microservice
spec:
  containers:
  - name: microservice
    image: sorelmitra/microservice:latest
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
  imagePullSecrets:
  - name: dockerhubcred
