# Uncomment the next line to define a global platform for your project
platform :ios, '13.3'

target 'chatmob' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatmob

  target 'chatmobTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chatmob-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatmob-tvOS

  target 'chatmob-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
