apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
