#!/bin/sh
APP=/usr/local/vim70/bin/gvim
PARAMS='--remote-send "<Esc>"'
if [ $# -gt 0 ]
then
  PARAMS='--remote-silent'
fi
CMD="$APP --servername GVIM2 $PARAMS $*"
$CMD
if [ $? -ne 0 ]
then
  $APP
fi

