/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "sorelm@juniper.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Helloworld C++"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Helloworld C++ 0.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "helloworld_cc"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.5"
