//
//  AppDelegate.h
//  HelloWorld
//
//  Created by Sorel Mitra on 3/24/14.
//
//

#import <Cocoa/Cocoa.h>

@class Track;

@interface AppDelegate : NSObject <NSApplicationDelegate>

// Generated by Xcode
@property (assign) IBOutlet NSWindow *window;

// Created by Ctrl-Dragging the text field to this header file and selecting "Outlet"
@property (weak) IBOutlet NSTextField *textField;

// The same as textField
@property (weak) IBOutlet NSSlider *slider;

// Created manually; in the interface the outlet was created by editing MainMenu.xib
@property (weak) IBOutlet NSComboBox *directionCombo;

// Created manually.
// This is a property, so the compiler will automatically generate setTrack: and track (getter) methods
@property (strong) Track *track;

// Created by Ctrl-Dragging the text field to this header file and selecting "Action"
- (IBAction)mute:(id)sender;

// The same as mute:
- (IBAction)takeFloatValueForVolumeFrom:(id)sender;

- (void)updateUserInterface;

@end
